### ISSUE TITLE
Carbone Roadmap

### ISSUE THREAD

**Issue by steevepay** [Ideolys/carbone#60]
Hello everyone, 

I would like to share the roadmap for CarboneJS and the team thoughts for the future! 🚀
First of all, thanks for the Github community for contributing and spreading the project. 
Carbone has been created for an internal project and we decided to open source it because of the increasing demand. We are glad to see a lot of you liked it! 💕A lot of evolutions, features, and issues are coming from the community in addition to the Carbone Team and we will consider every request.
There is only one main goal: to keep Carbone to be the fastest and easiest report generator 🔥

## Roadmap 🚂
The following list will be updated along with newly published releases.
- [ ] Update the documentation
- [ ] 1.5.X release:  synchronize our private branch with the Github branch. Next changes and features will be pushed on the open-source version to avoid branch differences.
- [ ] Format numbers as number for XLSX and ODS files #13 (coming for the next release 👀)
- [ ] Fix the most important issues #44 #57 #45 and many more....
- [ ] Manage the pull request #40
- [ ] Feature: use markers into formatters, example: `{d.fruit:isEqual(apple, {d.successMessage})}`
- [ ] Feature: add dynamic colors for XLSX/ODS files
- [ ] Evolution: print errors and warning when it missing markers
- [ ] Publish a Carbone Javascript SDK 
- [ ] Publish a lot of Carbone examples with specific use case

**Comment by HeyItsJs** [comment]
Hey guys, just found this tool a couple of days ago and it felt as if all my prayers were answered!! 😍  Couldn't thank you guys more! 

A humble request though. Can we prioritize XLSX support before everything else and release it earlier as compared to other features? Most of the business application users are comfortable working with Excel. Hence I believe it will be beneficial to everyone.

Also, the date of this roadmap issue worries me a little. Is there an active contribution going on it?

**Comment by steevepay** [comment]
Hello @HeyItsJs, 

>  just found this tool a couple of days ago and it felt as if all my prayers were answered!! 😍 Couldn't thank you guys more!

You are welcome!!

> A humble request though. Can we prioritize XLSX support before everything else and release it earlier as compared to other features? Most of the business application users are comfortable working with Excel. Hence I believe it will be beneficial to everyone.

Our next priority is to upgrade the error management, print accurate and relevant messages to make the design process smooth when a language typo occurs. Though, I consider your request, and XLSX support improvement will come after the error upgrades. However, a solution is available for you: Design ODS templates and export with Carbone as an XLSX document.

> Also, the date of this roadmap issue worries me a little. Is there an active contribution going on it?

Since the creation of the CarboneIO organization a few months ago, we have had a lot of administration and legal stuff to complete. In the meantime, we made many contributions to the Carbone Enterprise edition as the same as Carbone Community Edition. Updates are coming and I'm will update the roadmap pretty soon ;)
To get the latest news, latest work, or experimentations from the team, feel free to follow us on [Twitter](https://twitter.com/carbone_io).

Have a great day and enjoy creating with Carbone!! 🎉

**Comment by LDami** [comment]
Hello,

There is no code changes for at least one year, is this project still maintained?

**Comment by steevepay** [comment]
Hello @LDami,

Carbone is actively maintained.
The team is focused on the Enterprise version (Cloud API) in that way, we can continue the development and bring new features and fixes. We plan to publish a new version on Carbone Core (this repository) soon.

Follow the development on Twitter: https://twitter.com/carbone_io
The changelog: https://carbone.io/changelog.html

**Comment by graycrow** [comment]
Ok, I understand the concept of being behind by one major version and the reasons why you went that route. However, it seems that bugs are not fixed in the community version, is that true? For example, there are a few bug reports in this repository, but not a single code fix has been made in 10 months, while the Enterprise version gets patches several times a month.  If possible, can someone explain why it's not as bad as I think it is? Thanks.

**Comment by dgrelaud** [comment]
@graycrow Yes, we know it's not ideal. If you have a blocking issue, feel free to contact us directly via the chat on [our website](https://carbone.io/). No salesmen, just techs like me. The chat is our main communication channel.

If you want to access all patches along with all v4 features, please use [this Docker edition](https://hub.docker.com/r/carbone/carbone-ee). It starts with all community features  by default (no license) and is always up-to-date.

We primarily fix security issues in this v3 repository. Currently, our main focus is on Carbone v5. Everything takes time, and we have to prioritize what is going to bring the most value to everyone. We will do our best to clean up all issues in this repository when we will have more time (or more people), and when the v4 will be open sourced 🙏

**Comment by graycrow** [comment]
@dgrelaud, thanks for the clarification. In the meantime, my org has become a paying customer, so I'm using an Enterprise Edition now, so far everything is going well.

**Comment by maksim-yesman-covergo** [comment]
Hi everyone,

I'm just checking in on the status of this project. I noticed there haven't been [any code changes (other than to README.md)](https://github.com/carboneio/carbone/commits/master/) in over a year (since June 13, 2024).

The v5 release was scheduled for [mid-March 2025](https://carbone.io/company/carbone-v5-news.html), but it's now mid-September and there hasn't been any news.

Is the project still active? Any updates you can share would be greatly appreciated!

**Comment by dgrelaud** [comment]
@maksim-yesman-covergo  

The project is still active. We serve many customers worldwide, and the company is profitable.  
You can find all Carbone v4 / v5 updates on our [changelog page](https://carbone.io/changelog.html).

The Community Edition will be updated to v4 after the release of Carbone v5.  
Sorry, [This page](https://carbone.io/company/carbone-v5-news.html) is not up to date. Some technical changes and integration tests with certain clients have delayed the timeline.

We will gradually roll out the final v5 release to production this week (cloud first).
Over the past week, we closed about 45 issues in this public repository. 😉

Feel free to contact us in the chat if you need anything.

**Comment by maksim-yesman-covergo** [comment]
Got it, @dgrelaud. Thank you very much for the update and provided information!
